### ISSUE TITLE
Uable to fetch image_features_embedding.pkl file

### ISSUE THREAD

**Issue by asad0206** [sonu275981/Fashion-Recommender-system#6]
The file wont fetch via git lfs. Can you please send the file.

**Comment by sonu275981** [comment]
@asad0206 Please use this link to download

https://drive.google.com/file/d/1zQTfnzdJ7y_BYJ9Y4c0koeEGlpQVdONT/view?usp=share_link

once the download is complete pls let me know

**Comment by asad0206** [comment]
Yes, It's done.

But can you explain me once why does it take so long to generate it from scratch and what do I need to do If i need to make it fast and generate from scratch

**Comment by Shershon25** [comment]
@sonu275981 Hey! I also can't fetch the embeddings file. Can you send it again?

**Comment by sonu275981** [comment]
Hi @Shershon25 Please use this link to download

https://drive.google.com/file/d/1T2aVt5oTamGxDRfXyF01IxN5VLJ6-EoP/view?usp=sharing

**Once the download is complete pls let me know**

**Comment by sonu275981** [comment]
Hi @Shershon25  If you find it helpful, please like and follow

**Comment by sonu275981** [comment]
$${\color{red}Red}$$

**Comment by Shershon25** [comment]
Hey! I have downloaded it. Thanks!
