### ISSUE TITLE
Error while pulling the image_features_embedding.pkl 

### ISSUE THREAD

**Issue by kishoredas2001** [sonu275981/Fashion-Recommender-system#9]
Hi There , Could you please help me with the image_features_embedding.pkl large file I am unable to pull it from here.

**Comment by kishoredas2001** [comment]
@sonu275981 Please help me with this.

**Comment by kishoredas2001** [comment]
@sonu275981 Hello , Sonu sir Could you please me with the file ??

**Comment by sonu275981** [comment]
create your own .pkl file by training
